# .github/FUNDING.yml

# Muestra el botón de GitHub Sponsors.
# Necesitas tener tu perfil de GitHub Sponsors activado para que funcione.
github: [Marcorojas17]

# Añade enlaces de financiación personalizados.
# Puedes incluir hasta 4 URLs.
custom:
  - "https://link.mercadopago.com.mx/kronosprorocol"
  Ingresa al link, elige cómo pagar, ¡y listo! https://link.mercadopago.com.mx/kronosprorocol
